//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRA
    {
        public int hra_id { get; set; }
        public Nullable<System.DateTimeOffset> cas_prvni_tah { get; set; }
        public Nullable<System.DateTimeOffset> cas_posledni_tah { get; set; }
        public int pocet_oznacenych_min { get; set; }
        public Nullable<int> oblast { get; set; }
        public Nullable<int> stav { get; set; }
    
        public virtual OBLAST OBLAST1 { get; set; }
        public virtual STAV STAV1 { get; set; }
    }
}
