//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINA
    {
        public int mina_id { get; set; }
        public Nullable<int> souradnice_x { get; set; }
        public Nullable<int> souradnice_y { get; set; }
        public Nullable<int> oblast { get; set; }
    
        public virtual OBLAST OBLAST1 { get; set; }
    }
}
