//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMEZENI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OMEZENI()
        {
            this.OBTIZNOST = new HashSet<OBTIZNOST>();
        }
    
        public int omezeni_id { get; set; }
        public Nullable<int> sirka_max { get; set; }
        public Nullable<int> sirka_min { get; set; }
        public Nullable<int> vyska_max { get; set; }
        public Nullable<int> vyska_min { get; set; }
        public Nullable<int> pocet_min_max { get; set; }
        public Nullable<int> pocet_min_min { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBTIZNOST> OBTIZNOST { get; set; }
    }
}
