//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postgresEntities : DbContext
    {
        public postgresEntities()
            : base("name=postgresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HRA> HRA { get; set; }
        public virtual DbSet<MINA> MINA { get; set; }
        public virtual DbSet<OBLAST> OBLAST { get; set; }
        public virtual DbSet<OBTIZNOST> OBTIZNOST { get; set; }
        public virtual DbSet<OMEZENI> OMEZENI { get; set; }
        public virtual DbSet<POLE> POLE { get; set; }
        public virtual DbSet<STAV> STAV { get; set; }
        public virtual DbSet<TAH> TAH { get; set; }
    }
}
