//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAH
    {
        public int tah_id { get; set; }
        public int souradnice_x { get; set; }
        public int souradnice_y { get; set; }
        public System.DateTimeOffset cas_tahu { get; set; }
        public Nullable<int> oblast { get; set; }
    
        public virtual OBLAST OBLAST1 { get; set; }
    }
}
